my
    text hello;  This is USER-Production Enviroment 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://172.16.13.129:8560/eureka
spring
     datasource
         url jdbcmysqllocalhost3306mysql_maindb_Production
         username root
         password 123456
         driverclassname com.mysql.cj.jdbc.Driver
       jpa
          hibernate
            ddl-auto update
            dialect org.hibernate.dialect.MySQL8Dialect
            show-sql true
          properties
             hibernate.format_sql true
             hibernate.generate_statistics true  
  
